# Generated by Django 2.2.9 on 2022-08-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20220823_0451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.Group",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="post",
            order_with_respect_to="pub_date",
        ),
    ]
