# Generated by Django 2.2.9 on 2022-08-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20220824_1354"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-pub_date"]},
        ),
        migrations.AlterOrderWithRespectTo(
            name="post",
            order_with_respect_to=None,
        ),
    ]
